# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MixerMaker-1.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Mixer = QtWidgets.QWidget()
        self.Mixer.setObjectName("Mixer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Mixer)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.Mixer)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.comboBoxPickMixer = QtWidgets.QComboBox(self.Mixer)
        self.comboBoxPickMixer.setEditable(True)
        self.comboBoxPickMixer.setObjectName("comboBoxPickMixer")
        self.gridLayout.addWidget(self.comboBoxPickMixer, 2, 3, 1, 1)
        self.lineEditModel = QtWidgets.QLineEdit(self.Mixer)
        self.lineEditModel.setObjectName("lineEditModel")
        self.gridLayout.addWidget(self.lineEditModel, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.Mixer)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        self.lineEditBrand = QtWidgets.QLineEdit(self.Mixer)
        self.lineEditBrand.setPlaceholderText("")
        self.lineEditBrand.setObjectName("lineEditBrand")
        self.gridLayout.addWidget(self.lineEditBrand, 4, 3, 1, 1)
        self.labelBrand = QtWidgets.QLabel(self.Mixer)
        self.labelBrand.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelBrand.setObjectName("labelBrand")
        self.gridLayout.addWidget(self.labelBrand, 4, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.Mixer)
        self.label_3.setEnabled(False)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Mixer)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBoxMuteStyle = QtWidgets.QComboBox(self.Mixer)
        self.comboBoxMuteStyle.setObjectName("comboBoxMuteStyle")
        self.comboBoxMuteStyle.addItem("")
        self.comboBoxMuteStyle.addItem("")
        self.gridLayout_5.addWidget(self.comboBoxMuteStyle, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Mixer)
        self.label_2.setEnabled(False)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.Mixer)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Mixer)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 2, 2, 1, 1)
        self.radioButtonOSC = QtWidgets.QRadioButton(self.Mixer)
        self.radioButtonOSC.setCheckable(True)
        self.radioButtonOSC.setChecked(True)
        self.radioButtonOSC.setObjectName("radioButtonOSC")
        self.gridLayout_5.addWidget(self.radioButtonOSC, 1, 0, 1, 1)
        self.radioButtonMIDI = QtWidgets.QRadioButton(self.Mixer)
        self.radioButtonMIDI.setObjectName("radioButtonMIDI")
        self.gridLayout_5.addWidget(self.radioButtonMIDI, 2, 0, 1, 1)
        self.comboBoxCountBase = QtWidgets.QComboBox(self.Mixer)
        self.comboBoxCountBase.setObjectName("comboBoxCountBase")
        self.comboBoxCountBase.addItem("")
        self.comboBoxCountBase.addItem("")
        self.gridLayout_5.addWidget(self.comboBoxCountBase, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.Mixer)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 6, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Mixer, "")
        self.Strips = QtWidgets.QWidget()
        self.Strips.setObjectName("Strips")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Strips)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonAddStrip = QtWidgets.QPushButton(self.Strips)
        self.pushButtonAddStrip.setObjectName("pushButtonAddStrip")
        self.gridLayout_3.addWidget(self.pushButtonAddStrip, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Strips)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.Strips)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 2, 0, 1, 3)
        self.pushButtonEditStrip = QtWidgets.QPushButton(self.Strips)
        self.pushButtonEditStrip.setObjectName("pushButtonEditStrip")
        self.gridLayout_3.addWidget(self.pushButtonEditStrip, 1, 1, 1, 1)
        self.pushButtonRemoveStrip = QtWidgets.QPushButton(self.Strips)
        self.pushButtonRemoveStrip.setObjectName("pushButtonRemoveStrip")
        self.gridLayout_3.addWidget(self.pushButtonRemoveStrip, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Strips, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_7.setBuddy(self.comboBoxPickMixer)
        self.label.setBuddy(self.lineEditModel)
        self.labelBrand.setBuddy(self.lineEditBrand)
        self.label_3.setBuddy(self.lineEdit_2)
        self.label_2.setBuddy(self.lineEdit)
        self.label_6.setBuddy(self.comboBoxCountBase)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Select:"))
        self.label.setText(_translate("MainWindow", "Model"))
        self.labelBrand.setText(_translate("MainWindow", "Brand"))
        self.label_3.setText(_translate("MainWindow", "MIDI Adress"))
        self.label_4.setText(_translate("MainWindow", "Mute Style"))
        self.comboBoxMuteStyle.setItemText(0, _translate("MainWindow", "Muted When Illuminated"))
        self.comboBoxMuteStyle.setItemText(1, _translate("MainWindow", "Muted When Dark"))
        self.label_2.setText(_translate("MainWindow", "IP Address"))
        self.radioButtonOSC.setText(_translate("MainWindow", "OSC"))
        self.radioButtonMIDI.setText(_translate("MainWindow", "MIDI"))
        self.comboBoxCountBase.setItemText(0, _translate("MainWindow", "0"))
        self.comboBoxCountBase.setItemText(1, _translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "Count Base"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Mixer), _translate("MainWindow", "Mixer"))
        self.pushButtonAddStrip.setText(_translate("MainWindow", "Add"))
        self.label_5.setText(_translate("MainWindow", "Configure Mixer Strips"))
        self.pushButtonEditStrip.setText(_translate("MainWindow", "Edit"))
        self.pushButtonRemoveStrip.setText(_translate("MainWindow", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Strips), _translate("MainWindow", "Strips"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

