# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StripEdit.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 441)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777212))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_Name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.gridLayout.addWidget(self.lineEdit_Name, 2, 1, 3, 2)
        self.lineEdit_Count = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Count.setObjectName("lineEdit_Count")
        self.gridLayout.addWidget(self.lineEdit_Count, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 3, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.comboBox_StripType = QtWidgets.QComboBox(Dialog)
        self.comboBox_StripType.setEditable(True)
        self.comboBox_StripType.setObjectName("comboBox_StripType")
        self.comboBox_StripType.addItem("")
        self.comboBox_StripType.addItem("")
        self.comboBox_StripType.addItem("")
        self.comboBox_StripType.addItem("")
        self.comboBox_StripType.addItem("")
        self.comboBox_StripType.addItem("")
        self.comboBox_StripType.addItem("")
        self.gridLayout.addWidget(self.comboBox_StripType, 0, 1, 1, 2)
        self.label_Controls = QtWidgets.QLabel(Dialog)
        self.label_Controls.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Controls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Controls.setLineWidth(5)
        self.label_Controls.setText("")
        self.label_Controls.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Controls.setObjectName("label_Controls")
        self.gridLayout.addWidget(self.label_Controls, 5, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Mixer Strip"))
        self.label_2.setText(_translate("Dialog", "Count"))
        self.label_3.setText(_translate("Dialog", "Strip Type"))
        self.lineEdit_Name.setToolTip(_translate("Dialog", "Strip name or header, typically Ch, Bus, Aux"))
        self.lineEdit_Count.setToolTip(_translate("Dialog", "Number of strips of this type, max = 99"))
        self.label.setText(_translate("Dialog", "Name"))
        self.label_4.setText(_translate("Dialog", "Controls"))
        self.comboBox_StripType.setItemText(0, _translate("Dialog", "input"))
        self.comboBox_StripType.setItemText(1, _translate("Dialog", "auxin"))
        self.comboBox_StripType.setItemText(2, _translate("Dialog", "bus"))
        self.comboBox_StripType.setItemText(3, _translate("Dialog", "main"))
        self.comboBox_StripType.setItemText(4, _translate("Dialog", "stout"))
        self.comboBox_StripType.setItemText(5, _translate("Dialog", "auxmaster"))
        self.comboBox_StripType.setItemText(6, _translate("Dialog", "busmaster"))
        self.label_Controls.setToolTip(_translate("Dialog", "Right click to Edit/Add/Remove controls on this strip."))

