# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowMixer_r5.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.stripgridLayout = QtWidgets.QGridLayout()
        self.stripgridLayout.setObjectName("stripgridLayout")
        self.verticalLayout.addLayout(self.stripgridLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setMinimumSize(QtCore.QSize(0, 200))
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_2.addWidget(self.tableView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.row_focus_upButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.row_focus_upButton.sizePolicy().hasHeightForWidth())
        self.row_focus_upButton.setSizePolicy(sizePolicy)
        self.row_focus_upButton.setMinimumSize(QtCore.QSize(0, 0))
        self.row_focus_upButton.setAutoFillBackground(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Res/UpChevron.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.row_focus_upButton.setIcon(icon)
        self.row_focus_upButton.setIconSize(QtCore.QSize(32, 32))
        self.row_focus_upButton.setAutoRepeat(False)
        self.row_focus_upButton.setAutoDefault(False)
        self.row_focus_upButton.setObjectName("row_focus_upButton")
        self.verticalLayout_2.addWidget(self.row_focus_upButton)
        self.row_focus_downButton = QtWidgets.QPushButton(self.centralwidget)
        self.row_focus_downButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Res/DnChevron.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.row_focus_downButton.setIcon(icon1)
        self.row_focus_downButton.setIconSize(QtCore.QSize(32, 32))
        self.row_focus_downButton.setAutoRepeat(False)
        self.row_focus_downButton.setObjectName("row_focus_downButton")
        self.verticalLayout_2.addWidget(self.row_focus_downButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.butonsLayout = QtWidgets.QHBoxLayout()
        self.butonsLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.butonsLayout.setObjectName("butonsLayout")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setObjectName("nextButton")
        self.butonsLayout.addWidget(self.nextButton)
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevButton.sizePolicy().hasHeightForWidth())
        self.prevButton.setSizePolicy(sizePolicy)
        self.prevButton.setObjectName("prevButton")
        self.butonsLayout.addWidget(self.prevButton)
        self.jumpButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jumpButton.sizePolicy().hasHeightForWidth())
        self.jumpButton.setSizePolicy(sizePolicy)
        self.jumpButton.setObjectName("jumpButton")
        self.butonsLayout.addWidget(self.jumpButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.butonsLayout.addItem(spacerItem4)
        self.savecueButton = QtWidgets.QPushButton(self.centralwidget)
        self.savecueButton.setObjectName("savecueButton")
        self.butonsLayout.addWidget(self.savecueButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.butonsLayout.addItem(spacerItem5)
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quitButton.sizePolicy().hasHeightForWidth())
        self.quitButton.setSizePolicy(sizePolicy)
        self.quitButton.setObjectName("quitButton")
        self.butonsLayout.addWidget(self.quitButton)
        self.verticalLayout.addLayout(self.butonsLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(80, 80))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_Show = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Res/open_base.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Show.setIcon(icon2)
        self.actionOpen_Show.setObjectName("actionOpen_Show")
        self.actionClose_Show = QtWidgets.QAction(MainWindow)
        self.actionClose_Show.setObjectName("actionClose_Show")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Show = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Res/close_base.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Show.setIcon(icon3)
        self.actionSave_Show.setObjectName("actionSave_Show")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionUpdate_Cue = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Res/Update_base.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_Cue.setIcon(icon4)
        self.actionUpdate_Cue.setObjectName("actionUpdate_Cue")
        self.menuFile.addAction(self.actionOpen_Show)
        self.menuFile.addAction(self.actionSave_Show)
        self.menuFile.addAction(self.actionClose_Show)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.toolBar.addAction(self.actionSave_Show)
        self.toolBar.addAction(self.actionUpdate_Cue)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        self.actionExit.triggered.connect(MainWindow.close)
        self.quitButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Show Mixer"))
        self.row_focus_upButton.setToolTip(_translate("MainWindow", "Select previous"))
        self.row_focus_downButton.setToolTip(_translate("MainWindow", "Select next"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.prevButton.setText(_translate("MainWindow", "Previous"))
        self.jumpButton.setText(_translate("MainWindow", "Jump"))
        self.savecueButton.setText(_translate("MainWindow", "Save Cue"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_Show.setText(_translate("MainWindow", "Open Show"))
        self.actionClose_Show.setText(_translate("MainWindow", "Close Show"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_Show.setText(_translate("MainWindow", "Save Show"))
        self.actionSave_Show.setToolTip(_translate("MainWindow", "Save current state of mutes and levels"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionUpdate_Cue.setText(_translate("MainWindow", "Update Cue"))
        self.actionUpdate_Cue.setToolTip(_translate("MainWindow", "Update cue table"))

import ShowMixer_rsrc_rc
